[gtest] Disable POSIX regular expressions if __embedded__ is set.
devkitPPC has declarations for the POSIX RE functions, but they aren't
actually implemented. Attempting to build gtest without this change
results in the following errors:

Linking CXX executable ByteswapTest
../../../extlib/gtest/libgtest.a(gtest-all.cc.o): In function `testing::internal::RE::~RE()':
extlib/gtest/src/gtest-port.cc:146: undefined reference to `regfree'
extlib/gtest/src/gtest-port.cc:147: undefined reference to `regfree'
../../../extlib/gtest/libgtest.a(gtest-all.cc.o): In function `testing::internal::RE::FullMatch(char const*, testing::internal::RE const&)':
extlib/gtest/src/gtest-port.cc:157: undefined reference to `regexec'
../../../extlib/gtest/libgtest.a(gtest-all.cc.o): In function `testing::internal::RE::PartialMatch(char const*, testing::internal::RE const&)':
extlib/gtest/src/gtest-port.cc:166: undefined reference to `regexec'
../../../extlib/gtest/libgtest.a(gtest-all.cc.o): In function `testing::internal::CapturedStream::GetCapturedString()':
extlib/gtest/src/gtest-port.cc:572: undefined reference to `dup2'
../../../extlib/gtest/libgtest.a(gtest-all.cc.o): In function `CapturedStream':
extlib/gtest/src/gtest-port.cc:516: undefined reference to `dup'
extlib/gtest/src/gtest-port.cc:560: undefined reference to `dup2'
../../../extlib/gtest/libgtest.a(gtest-all.cc.o): In function `testing::internal::RE::Init(char const*)':
extlib/gtest/src/gtest-port.cc:179: undefined reference to `regcomp'
extlib/gtest/src/gtest-port.cc:190: undefined reference to `regcomp'
collect2: error: ld returned 1 exit status
src/libcompat/tests/CMakeFiles/ByteswapTest.dir/build.make:140: recipe for target 'src/libcompat/tests/ByteswapTest' failed

The dup() and dup2() symbols are still missing, so it still doesn't link.

In addition to fixing the undefined symbols, I'll need to add stub code
to set up the console. Otherwise, it'll end up printing to nowhere.